### Define Variables ###

# Version #
KRepoTool_Version="0.3.3"

# Dists #
# Define which Fedora releases to query #
# Superceded by $InstalledReleaseVer, but kept here in case a query is desired for a different version other than what is installed.
dists="(42 43 rawhide)"
export dists


# Repo #
Repo_BaseURL="https://download.copr.fedorainfracloud.org/results/@kernel-vanilla"
Repo_Arch="x86_64"

# RepoQueryArgs #
# NEW: Repo Query Args #
RepoQueryArgs=" --quiet ${repostring} --disablerepo=* --enablerepo=kvr-* --latest-limit=1 -q kernel --arch x86_64 --qf '%{version}-%{release}'"

# Printf #
# Define the format string with fixed widths and left alignment (%-Xs)
#   %-15s: left-align string in a 15-char width
#   %-8s: left-align string in an 8-char width
#   %-10s: left-align string in a 10-char width
#   \n: newline character
  	# FORMAT="%-15s | %-8s | %-10s\n"

Printf_Format="%-20s %-10s %s\n"
